trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
pr: none

stages:
- stage: Build
  jobs:
  - job: WindowsServer2019
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      submodules: true | recursive
    - template: build/azure-pipelines/windows/continuous-build.yml
