# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - docker

variables:
  - name: TESTVAR1
    value: value1
  - name: TESTVAR2
    value: value2

jobs:
- job: 'Ubuntu_1604'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - script: |
      whoami
      cat /etc/*release
      lscpu
      df -h
      free
  - script: |
      printenv
  - script: |
      echo $TESTVAR1
      echo $TESTVAR2
      docker version
  - script: |
      docker run -t --rm ubuntu:16.04 bash -c 'whoami; cat /etc/*release; lscpu; df -h; free; printenv'
      docker images
      docker ps

- job: 'Container'
  container: ubuntu:16.04
  steps:
  - script: |
      whoami
      cat /etc/*release
      lscpu
      df -h
      free
  - script: |
      printenv
  - script: |
      echo $TESTVAR1
      echo $TESTVAR2