# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- sudo

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    apt-get update
    apt-get install htop
  displayName: 'Sudo'
