# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  variables:
    var1: value1
  jobs:
  - job: 'Ubuntu_1604'
    continueOnError: false
    pool:
      vmImage: 'ubuntu-16.04'
    workspace:
      clean: all
    timeoutInMinutes: 5
    steps:
    - script: |
        whoami
        cat /etc/*release
        lscpu
        df -h
        free
    - script: |
        printenv
    - script: |
        echo 2
        echo $var1
- stage: Test
  jobs:
  - job: 'Ubuntu_1604'
    steps:
    - script: |
        echo running tests..
        echo $var1
- stage: Parallel
  dependsOn: []
  jobs:
  - job: 'Ubuntu_1604'
    steps:
    - script: |
        echo running parallel tasks..
