# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - vm

variables:
  - name: TESTVAR1
    value: value1
  - name: TESTVAR2
    value: value2

jobs:
- job: 'Ubuntu_1604'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  timeoutInMinutes: 5
  strategy:
    matrix:
      Matrix1:
        MATRIX_VAR: 'matrix1'
        parallel: 2
      Matrix2:
        MATRIX_VAR: 'matrix2'
        parallel: 2
      Matrix3:
        MATRIX_VAR: 'matrix3'
      Matrix4:
        MATRIX_VAR: 'matrix4'
      Matrix5:
        MATRIX_VAR: 'matrix5'
      Matrix6:
        MATRIX_VAR: 'matrix6'
  steps:
  - script: |
      whoami
      cat /etc/*release
      lscpu
      df -h
      free
    displayName: 'System Info'
  - script: |
      printenv
    displayName: 'Environment variables'
  - script: |
      echo $TESTVAR1
      echo $TESTVAR2
      echo $MATRIX_VAR
      docker version
      docker run -t --rm ubuntu:16.04 bash -c 'whoami; cat /etc/*release; lscpu; df -h; free; printenv'
      docker images
      docker ps -a
      docker volume ls