# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - powershell

jobs:
- job: 'PowerShell_2'
  continueOnError: false
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - powershell: |
      systeminfo
      Get-PSDrive
      $($PSVersionTable | Out-String).Trim()
  - pwsh: |
      $PSVersionTable

- job: 'PowerShell_3'
  continueOnError: false
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - powershell: |
      systeminfo
      Get-PSDrive
      $($PSVersionTable | Out-String).Trim()
  - pwsh: |
      $PSVersionTable

- job: 'PowerShell_4'
  continueOnError: false
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - powershell: |
      systeminfo
      Get-PSDrive
      $($PSVersionTable | Out-String).Trim()
  - pwsh: |
      $PSVersionTable

- job: 'PowerShell_Core'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - script: |
      whoami
      cat /etc/*release
      lscpu
      df -h
      free
  - pwsh: |
      $PSVersionTable