# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    # - tags
    # - build/*
    - '*'
  tags:
    include:
      - '*'

variables:
  - name: GLOBAL_VAR1
    value: global1
  - name: GLOBAL_VAR2
    value: global2

stages:
- stage: Build_Test_Publish
  displayName: Build, Test, Publish
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
    - bash: |
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
    # - task: GitHubRelease@0
    #   inputs:
    #     gitHubConnection: release
    #     repositoryName: $(Build.Repository.Name)
    #     action: create # Options: create, edit, delete
    #     target: $(Build.SourceVersion) # Required when action == Create || Action == Edit
    #     tagSource: auto # Required when action == Create# Options: auto, manual
    #     # tagPattern: # Optional
    #     # tag: # Required when action == Edit || Action == Delete || TagSource == Manual
    #     # title: # Optional
    #     # releaseNotesSource: input # Optional. Options: file, input
    #     # releaseNotesFile: # Optional
    #     # releaseNotes: # Optional
    #     # assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
    #     # assetUploadMode: 'delete' # Optional. Options: delete, replace
    #     isDraft: false # Optional
    #     isPreRelease: false # Optional
    #     addChangeLog: true # Optional
    #     # compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
    #     # releaseTag: # Required when compareWith == LastReleaseByTag
    #     changeLogCompareToRelease: 'lastFullRelease'
    #     changeLogType: 'issueBased'
    #     changeLogLabels: |
    #       [
    #       { "label" : "bug", "displayName" : "Bugs", "state" : "closed" },
    #       { "label" : "debug", "displayName" : "Debug", "state" : "closed" }
    #       ]

    - pwsh: |
        $releaseBody = @"
        \# Changelog

        \## $commitTag ($(Get-Date -UFormat '%Y-%m-%d'))

        $changeLog
        "@
      displayName: Create GitHub Release
