# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr: none

stages:
- stage: stage_1
  jobs:
  - job: job_1
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - pwsh: 'hi'
  - job: job_2
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: self
      submodules: recursive
    - bash: 'echo hi'
- stage: stage_2
  dependsOn:
  - stage_1
  jobs:
  - job: job_1
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - pwsh: 'hi'
