# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - docker

variables:
  - name: TESTVAR1
    value: value1
  - name: TESTVAR2
    value: value2

jobs:
- job: 'Ubuntu_1604'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - script: |
      whoami
      cat /etc/*release
      lscpu
      df -h
      free
  - script: |
      printenv
  - script: | 
      echo $TESTVAR1
      echo $TESTVAR2
  - script: |
      docker version