# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: WindowsServer2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: WindowsServer2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: WindowsServer1803
  pool:
    vmImage: 'win1803'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: WindowsServer2012R2
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  # - pwsh: |
  #     Get-PSDrive
  #     $PSVersionTable | Format-Table

- job: Ubuntu1804
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: Ubuntu1604
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: macOS1015
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: macOS1014
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table

- job: macOS1013
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - powershell: |
      Get-PSDrive
      $PSVersionTable | Format-Table
  - pwsh: |
      Get-PSDrive
      $PSVersionTable | Format-Table
