trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr: none

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: joeltimothyoh
    ref: refs/heads/dev

stages:
- stage: Build_Test
  displayName: Build, Test
  jobs:
  - job: windows2019
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: true
    - powershell: |
        Get-ChildItem -Recurse
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (powershell)
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (powershell)
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (powershell)
    # - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
  - job: vs2017win2016
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: self
      submodules: true
    - powershell: |
        Get-ChildItem -Recurse
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (powershell)
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (powershell)
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (powershell)
    # - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
  - job: win1803
    pool:
      vmImage: win1803
    steps:
    - checkout: self
      submodules: true
    - powershell: |
        Get-ChildItem -Recurse
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (powershell)
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (powershell)
    - pwsh: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (powershell)
    # - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
  - job: vs2015win2012r2
    pool:
      vmImage: vs2015-win2012r2
    steps:
    - checkout: self
      submodules: true
    - powershell: |
        Get-ChildItem -Recurse
    # - pwsh: |
    #     $ErrorActionPreference = 'Stop'
    #     $VerbosePreference = 'Continue'
    #     $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    #     "Elevated: $elevated"
    #   displayName: Check for elevation (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        $elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        "Elevated: $elevated"
      displayName: Check for elevation (powershell)
    # - pwsh: |
    #     $ErrorActionPreference = 'Stop'
    #     $VerbosePreference = 'Continue'
    #     Get-Module PowerShellGet -ListAvailable | Select *
    #     Get-Module PackageManagement -ListAvailable | Select *
        # Get-PackageProvider NuGet | Select *
    #   displayName: Check installed modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
        Get-PackageProvider NuGet | Select *
      displayName: Check installed modules (powershell)
    # - pwsh: |
    #     $ErrorActionPreference = 'Stop'
    #     $VerbosePreference = 'Continue'
    #     "Installing PowerShellGet" | Write-Host
    #     $powershellGetRequiredVersion = '2.1.2'
    #     $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
    #     if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
    #         Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force
    #     }
    #     Get-Module PowerShellGet -ListAvailable | Select *
    #     Get-Module PackageManagement -ListAvailable | Select *
    #   displayName: Install modules (pwsh)
    - powershell: |
        $ErrorActionPreference = 'Stop'
        $VerbosePreference = 'Continue'
        "Installing PowerShellGet" | Write-Host
        $powershellGetRequiredVersion = '2.1.2'
        $powershellGetInstalledVersions = (Get-Module 'PowerShellGet' -ListAvailable).Version | % { $_.ToString() }
        if ($powershellGetRequiredVersion -notin $powershellGetInstalledVersions) {
            Install-Module -Name 'PowershellGet' -Repository 'PSGallery' -RequiredVersion $powershellGetRequiredVersion -Scope CurrentUser -Force -Confirm:$false
        }
        Get-Module PowerShellGet -ListAvailable | Select *
        Get-Module PackageManagement -ListAvailable | Select *
      displayName: Install modules (powershell)
    # - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
  - job: ubuntu1604
    pool:
      vmImage: ubuntu-16.04
    container: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git
    steps:
    - checkout: self
      submodules: true
    - pwsh: |
        Get-ChildItem -Recurse
    - pwsh: |
        Get-Module PowerShellGet -ListAvailable | Select *
    # - template: azure-pipelines/linux/continuous-build.yml@PSModulePublisher
  - job: macOS1014
    pool:
      vmImage: macOS-10.14
    steps:
    - checkout: self
      submodules: true
    - pwsh: |
        Get-ChildItem -Recurse
    - pwsh: |
        Get-Module PowerShellGet -ListAvailable | Select *
    # - template: azure-pipelines/macos/continuous-build.yml@PSModulePublisher
  - job: macOS1013
    pool:
      vmImage: macOS-10.13
    steps:
    - checkout: self
      submodules: true
    - pwsh: |
        Get-ChildItem -Recurse
    - pwsh: |
        Get-Module PowerShellGet -ListAvailable | Select *
    # - template: azure-pipelines/macos/continuous-build.yml@PSModulePublisher
# - stage: Publish
#   # dependsOn:
#   # - Build_Test
#   jobs:
#   - job: Windows
#     pool:
#       vmImage: windows-2019
#     steps:
#     - checkout: self
#       submodules: true
#     - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
#     - template: azure-pipelines/common/run-publish.yml@PSModulePublisher
