# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  GLOBAL_VAR1: global1

stages:
- stage: Build
  variables:
    STAGE_VAR1: stage1
  jobs:
  - job: 'job1'
    continueOnError: false
    pool:
      vmImage: 'ubuntu-16.04'
    workspace:
      clean: all
    timeoutInMinutes: 5
    variables:
      JOB_VAR1: job1
    strategy:
      matrix:
        Matrix1:
          MATRIX_VAR: 'matrix1'
        Matrix2:
          MATRIX_VAR: 'matrix2'
        Matrix3:
          MATRIX_VAR: 'matrix3'
    steps:
    - script: |
        whoami
        cat /etc/*release
        lscpu
        df -h
        free
    - script: |
        printenv
    - script: |
        echo running job..
        echo $GLOBAL_VAR1
        echo $STAGE_VAR1
        echo $JOB_VAR1
        echo $MATRIX_VAR
  - job: 'job2'
    continueOnError: false
    pool:
      vmImage: 'ubuntu-16.04'
    workspace:
      clean: all
    timeoutInMinutes: 5
    variables:
      JOB_VAR1: job1
    strategy:
      parallel: 2
    steps:
    - script: |
        whoami
        cat /etc/*release
        lscpu
        df -h
        free
    - script: |
        printenv
    - script: |
        echo running job..
        echo $GLOBAL_VAR1
        echo $STAGE_VAR1
        echo $JOB_VAR1
        echo $MATRIX_VAR
- stage: Test
  jobs:
  - job: 'job1'
    steps:
    - script: |
        echo running tests..
        echo $GLOBAL_VAR1
        echo $STAGE_VAR1
        echo $JOB_VAR1
- stage: Parallel
  dependsOn: []
  jobs:
  - job: 'job1'
    steps:
    - script: |
        echo running parallel tasks..
        echo $GLOBAL_VAR1
        echo $STAGE_VAR1
        echo $JOB_VAR1
        echo $MATRIX_VAR
