trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr: none

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: joeltimothyoh
    ref: refs/heads/dev

stages:
- stage: Build_Test
  displayName: Build, Test

  jobs:
  - job: windows2019
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-pwsh.yml
  - job: vs2017win2016
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-pwsh.yml
  - job: win1803
    pool:
      vmImage: win1803
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-pwsh.yml

  - job: windows2019_powershell
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-powershell.yml
  - job: vs2017win2016_powershell
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-powershell.yml
  - job: win1803_powershell
    pool:
      vmImage: win1803
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-powershell.yml
  - job: vs2015win2012r2
    pool:
      vmImage: vs2015-win2012r2
    steps:
    - checkout: self
      submodules: true
    - template: azure-pipelines/windows-powershell.yml

  # - job: ubuntu1604
  #   pool:
  #     vmImage: ubuntu-16.04
  #   # container: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git
  #   steps:
  #   - checkout: self
  #     submodules: true
  #   - template: azure-pipelines/linux.yml

  # - job: macOS1013
  #   pool:
  #     vmImage: macOS-10.13
  #   steps:
  #   - checkout: self
  #     submodules: true
  #   - template: azure-pipelines/macos.yml




# - stage: Publish
#   # dependsOn:
#   # - Build_Test
#   jobs:
#   - job: Windows
#     pool:
#       vmImage: windows-2019
#     steps:
#     - checkout: self
#       submodules: true
#     - template: azure-pipelines/windows/continuous-build.yml@PSModulePublisher
#     - template: azure-pipelines/common/run-publish.yml@PSModulePublisher
