# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- debug

jobs:
- job: WindowsServer2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: echo hello from Windows

- job: WindowsServer2016
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows

- job: WindowsServer2012R2
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: echo hello from Windows

- job: WindowsServer1803
  pool:
    vmImage: 'win1803'
  steps:
  - script: echo hello from Windows

- job: macOS1013
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo hello from macOS

- job: Ubuntu1604
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux