# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - powershell

jobs:
- job: 'PowerShell_2'
  continueOnError: false
  pool:
    vmImage: 'vs2015-win2012r2'
    demands:
      - ps2
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - powershell: |
      systeminfo
      Get-PSDrive
      $($PSVersionTable | Out-String).Trim()
  - powershell: |
      Get-ChildItem

- job: 'PowerShell_3'
  continueOnError: false
  pool:
    vmImage: 'vs2015-win2012r2'
    demands:
      - ps3
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - powershell: |
      systeminfo
      Get-PSDrive
      $($PSVersionTable | Out-String).Trim()
  - powershell: |
      Get-ChildItem

- job: 'PowerShell_4'
  continueOnError: false
  pool:
    vmImage: 'vs2015-win2012r2'
    demands:
      - ps4
  workspace:
    clean: all
  timeoutInMinutes: 5
  steps:
  - powershell: |
      systeminfo
      Get-PSDrive
      $($PSVersionTable | Out-String).Trim()
  - powershell: |
      Get-ChildItem